74 cadastro receitas frontend
UnBArqDsw/2020.1_G3_RecipeBuk_Frontend pull request #7
Opened 2020-10-22 15:42 UTC by leticiaarj

2020-10-26 17:30 UTC, SamButers requested changes

2020-10-26 17:30 UTC, SamButers commented on src/app/cadastro-receitas/cadastro-receitas.component.html
> +                        appearance = "outline"
Incluir placeholder para deixar claro o que o campo pede.

2020-10-26 17:30 UTC, SamButers commented on src/app/cadastro-receitas/cadastro-receitas.component.html
> +                    <input
Incluir placeholder para deixar claro o que o campo pede.

2020-10-26 17:30 UTC, SamButers commented on package.json
>    "devDependencies": {
Adicionar os pacotes @angular/cdk e @angular/material.

2020-10-26 18:03 UTC, larissa-sales commented on package.json
>    "devDependencies": {
em dependencies ou devDependencies? e você sabe a versão deles?

2020-10-26 18:18 UTC, SamButers commented on package.json
>    "devDependencies": {
Dependencies.
"@angular/material": "^10.2.5",
"@angular/cdk": "^10.2.5",

2020-10-27 14:43 UTC, SamButers requested changes

2020-10-27 14:43 UTC, SamButers commented on src/app/login/login.component.html
> +             <div class='row'>
Dois botões nessa branch.
Na dev isso está comentado.

2020-10-27 14:43 UTC, SamButers commented on src/app/cadastro/cadastro.component.html
> +             <div class='row'>
Dois botões nessa branch.
Na dev isso está comentado.

2020-10-31 00:48 UTC, larissa-sales commented on src/app/cadastro/cadastro.component.html
> +             <div class='row'>
Corrigido!

2020-10-31 00:48 UTC, larissa-sales commented on src/app/login/login.component.html
> +             <div class='row'>
Corrigido!

2020-10-31 00:55 UTC, SamButers approved these changes

2020-10-31 00:55 UTC, merged